export const TYPE_MAIN_STATE = 'TYPE_MAIN_STATE';
export const TYPE_ACCOUNT_INFO = 'TYPE_ACCOUNT_INFO';
export const TYPE_FOLDER_TREE = 'TYPE_FOLDER_TREE';
export const TYPE_FOLD_FOLDER_TREE = 'TYPE_FOLD_FOLDER_TREE';